'use client';

import { useMemo, useState } from 'react';
import {
  Activity,
  AlertCircle,
  Brain,
  CheckCircle2,
  Database,
  FlaskConical,
  LayoutDashboard,
  Loader2,
  Play,
  UserCheck,
} from 'lucide-react';

import { PageWrapper } from '@/components/layout/PageWrapper';

import {
  skyguardApi,
  type ApiScenario,
  type ApiScenarioResult,
} from '@/lib/api';

import { useStore } from '@/store/useStore';

const scenarios: ApiScenario[] = [
  {
    name: 'normal',
    description:
      'Stable readings from all five AWS stations.',
    expected_result: 'Normal',
  },
  {
    name: 'regional_storm',
    description:
      'Pressure falls and humidity rises coherently across the region.',
    expected_result: 'Genuine Weather Event',
  },
  {
    name: 'regional_heatwave',
    description:
      'Temperature rises coherently across neighbouring stations.',
    expected_result: 'Genuine Weather Event',
  },
  {
    name: 'temperature_spike',
    description:
      'One station reports an isolated impossible temperature spike.',
    expected_result: 'Sensor/Data Fault',
  },
  {
    name: 'frozen_sensor',
    description:
      'One sensor repeats identical values while neighbours change.',
    expected_result: 'Sensor/Data Fault',
  },
  {
    name: 'gradual_drift',
    description:
      'One sensor slowly drifts away from its neighbours.',
    expected_result: 'Sensor/Data Fault',
  },
  {
    name: 'dropout',
    description:
      'One sensor value becomes missing.',
    expected_result: 'Sensor/Data Fault',
  },
  {
    name: 'noise_burst',
    description:
      'One station oscillates while nearby stations remain stable.',
    expected_result: 'Sensor/Data Fault',
  },
  {
    name: 'timestamp_error',
    description:
      'One station sends an out-of-order timestamp.',
    expected_result: 'Sensor/Data Fault',
  },
  {
    name: 'ambiguous_change',
    description:
      'An unclear pattern is routed for human review.',
    expected_result: 'Uncertain - Human Review',
  },
];

const stages = [
  {
    icon: Activity,
    label: 'AWS Readings',
  },
  {
    icon: Database,
    label: 'Preprocessing',
  },
  {
    icon: Brain,
    label: 'Dual-Evidence AI',
  },
  {
    icon: LayoutDashboard,
    label: 'Classification',
  },
  {
    icon: UserCheck,
    label: 'Dashboard Update',
  },
];

function delay(milliseconds: number) {
  return new Promise<void>(resolve => {
    setTimeout(resolve, milliseconds);
  });
}

export default function SimulationPage() {
  const refreshFromApi = useStore(
    state => state.refreshFromApi
  );

  const dataSource = useStore(
    state => state.dataSource
  );

  const stations = useStore(
    state => state.stations
  );

  const [selectedScenario, setSelectedScenario] =
    useState('regional_storm');

  const [isRunning, setIsRunning] =
    useState(false);

  const [activeStage, setActiveStage] =
    useState(-1);

  const [result, setResult] =
    useState<ApiScenarioResult | null>(null);

  const [error, setError] =
    useState<string | null>(null);

  const [logs, setLogs] = useState<
    {
      time: string;
      message: string;
    }[]
  >([]);

  const selected = scenarios.find(
    scenario =>
      scenario.name === selectedScenario
  );

  const resultCounts = useMemo(() => {
    const counts: Record<string, number> = {};

    result?.final_results.forEach(reading => {
      counts[reading.classification] =
        (counts[reading.classification] ?? 0) + 1;
    });

    return counts;
  }, [result]);

  const addLog = (message: string) => {
    setLogs(current =>
      [
        {
          time: new Date().toLocaleTimeString(),
          message,
        },
        ...current,
      ].slice(0, 25)
    );
  };

  const runScenario = async () => {
    setIsRunning(true);
    setError(null);
    setResult(null);
    setActiveStage(0);

    addLog(`Starting: ${selectedScenario}`);

    try {
      await delay(250);

      setActiveStage(1);
      addLog('AWS readings generated by FastAPI.');

      await delay(250);

      setActiveStage(2);
      addLog(
        'Dual-Evidence Engine analysing data.'
      );

      const response =
        await skyguardApi.runScenario(
          selectedScenario
        );

      setActiveStage(3);

      addLog(
        `${response.readings_processed} readings processed.`
      );

      await refreshFromApi();
      await delay(250);

      setResult(response);
      setActiveStage(4);

      addLog(
        'Dashboard refreshed with ML results.'
      );
    } catch (caughtError) {
      const message =
        caughtError instanceof Error
          ? caughtError.message
          : 'Unable to run this scenario.';

      setError(message);
      setActiveStage(-1);

      addLog(`ERROR: ${message}`);
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <PageWrapper>
      <div className="space-y-6">
        <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-cyan-400">
              <FlaskConical className="h-4 w-4" />
              Judge Challenge Mode
            </p>

            <h1 className="text-3xl font-bold text-white">
              Real Backend Scenario Lab
            </h1>

            <p className="mt-2 text-sm text-slate-400">
              Send controlled AWS cases through the
              FastAPI and ML pipeline.
            </p>
          </div>

          <div className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-300">
            <span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.8)]" />

            {dataSource === 'api'
              ? 'Live API Data'
              : 'Fallback Data'}
          </div>
        </header>

        <section className="grid grid-cols-1 gap-4 sm:grid-cols-3">
          <Metric
            label="Connected Stations"
            value={stations.length}
          />

          <Metric
            label="Backend Scenarios"
            value={scenarios.length}
          />

          <Metric
            label="Last Result"
            value={result ? 'Completed' : 'Ready'}
          />
        </section>

        <section className="rounded-2xl border border-slate-800/70 bg-slate-900/50 p-6 shadow-xl">
          <div className="grid grid-cols-1 gap-5 md:grid-cols-5">
            {stages.map((stage, index) => {
              const Icon = stage.icon;

              const completed =
                activeStage > index;

              const active =
                activeStage === index;

              return (
                <div
                  key={stage.label}
                  className="flex flex-col items-center text-center"
                >
                  <div
                    className={`flex h-12 w-12 items-center justify-center rounded-full border transition-all ${
                      active
                        ? 'scale-110 border-cyan-400 bg-cyan-500/20 text-cyan-300 shadow-[0_0_22px_rgba(34,211,238,0.35)]'
                        : completed
                          ? 'border-emerald-500/30 bg-emerald-500/15 text-emerald-300'
                          : 'border-slate-700 bg-slate-800 text-slate-500'
                    }`}
                  >
                    {completed ? (
                      <CheckCircle2 className="h-5 w-5" />
                    ) : (
                      <Icon className="h-5 w-5" />
                    )}
                  </div>

                  <span className="mt-3 text-xs font-medium text-slate-300">
                    {stage.label}
                  </span>
                </div>
              );
            })}
          </div>
        </section>

        <section className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <div className="rounded-2xl border border-slate-800/70 bg-slate-900/50 p-6 shadow-xl">
            <h2 className="text-lg font-semibold text-white">
              Select a Challenge
            </h2>

            <label className="mt-5 block text-sm text-slate-400">
              Scenario
            </label>

            <select
              value={selectedScenario}
              disabled={isRunning}
              onChange={event =>
                setSelectedScenario(
                  event.target.value
                )
              }
              className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950/80 px-3 py-2.5 text-sm text-white outline-none focus:ring-2 focus:ring-cyan-500/50"
            >
              {scenarios.map(scenario => (
                <option
                  key={scenario.name}
                  value={scenario.name}
                >
                  {scenario.name
                    .replaceAll('_', ' ')
                    .replace(
                      /\b\w/g,
                      letter =>
                        letter.toUpperCase()
                    )}
                </option>
              ))}
            </select>

            <div className="mt-4 rounded-xl border border-slate-800 bg-slate-950/50 p-4">
              <p className="text-sm leading-6 text-slate-300">
                {selected?.description}
              </p>

              <p className="mt-3 text-xs font-semibold text-cyan-400">
                Expected:{' '}
                {selected?.expected_result}
              </p>
            </div>

            <button
              onClick={runScenario}
              disabled={isRunning}
              className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-600 px-4 py-3 text-sm font-bold text-white shadow-[0_0_20px_rgba(8,145,178,0.25)] transition hover:bg-cyan-500 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {isRunning ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Running Pipeline...
                </>
              ) : (
                <>
                  <Play className="h-4 w-4" />
                  Run Backend Scenario
                </>
              )}
            </button>

            {error && (
              <div className="mt-4 flex gap-2 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">
                <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
                {error}
              </div>
            )}
          </div>

          <div className="rounded-2xl border border-slate-800/70 bg-[#070b14] p-5 font-mono shadow-xl lg:col-span-2">
            <div className="mb-4 flex items-center justify-between border-b border-slate-800 pb-3">
              <h2 className="flex items-center gap-2 text-sm font-semibold text-slate-300">
                <Database className="h-4 w-4 text-cyan-400" />
                Live Pipeline Log
              </h2>

              <span className="text-xs text-slate-600">
                FastAPI :8000
              </span>
            </div>

            <div className="h-64 space-y-2 overflow-y-auto">
              {logs.map((log, index) => (
                <div
                  key={`${log.time}-${index}`}
                  className="flex gap-3 text-xs"
                >
                  <span className="shrink-0 text-slate-600">
                    [{log.time}]
                  </span>

                  <span
                    className={
                      log.message.startsWith(
                        'ERROR'
                      )
                        ? 'text-red-400'
                        : 'text-emerald-400'
                    }
                  >
                    {log.message}
                  </span>
                </div>
              ))}

              {logs.length === 0 && (
                <p className="text-xs italic text-slate-600">
                  Select a scenario and run the
                  pipeline.
                </p>
              )}
            </div>
          </div>
        </section>

        {result && (
          <section className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6">
            <h2 className="flex items-center gap-2 text-lg font-semibold text-white">
              <CheckCircle2 className="h-5 w-5 text-emerald-400" />
              Scenario Completed
            </h2>

            <div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
              {Object.entries(
                resultCounts
              ).map(
                ([
                  classification,
                  count,
                ]) => (
                  <div
                    key={classification}
                    className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"
                  >
                    <p className="text-xs text-slate-500">
                      {classification}
                    </p>

                    <p className="mt-2 text-2xl font-bold text-white">
                      {count}
                    </p>
                  </div>
                )
              )}
            </div>

            <p className="mt-4 text-xs leading-5 text-slate-500">
              {result.note}
            </p>
          </section>
        )}
      </div>
    </PageWrapper>
  );
}

function Metric({
  label,
  value,
}: {
  label: string;
  value: string | number;
}) {
  return (
    <div className="rounded-xl border border-slate-800/70 bg-slate-900/50 p-4">
      <p className="text-xs uppercase tracking-wider text-slate-500">
        {label}
      </p>

      <p className="mt-2 text-2xl font-bold text-white">
        {value}
      </p>
    </div>
  );
}